### ISSUE TITLE
send raw over socketio

### ISSUE THREAD

**Issue by notme1560** [shokai/websocket-client-simple#27]
Is it possible to send a raw piece of data over socketio? Like just a plain string

**Comment by unasuke** [comment]
@notme1560 This repository was moved [ruby-jp/websocket-client-simple](https://github.com/ruby-jp/websocket-client-simple). If you still need this, make pull request or issue to [ruby-jp/websocket-client-simple](https://github.com/ruby-jp/websocket-client-simple) again, thx.
